### ISSUE TITLE
Processes not getting closed properly on Windows

### ISSUE THREAD

**Issue by BoladoLimited** [ysmood/leakless#2]
On v0.6.9,  closing the program window after launching a browser with rod wouldn't close the program completely and still would leave chrome processes opened. 

Going back-and-forth to v0.6.8 and v0.6.9, changing nothing but leakless version on go.mod, the problem would only happen when the program was using v0.6.9.

I think it's an annoying problem as by default newer versions of go-rod are using v0.6.9 of leakess 😀

**Comment by ysmood** [comment]
Sure, take care of Windows is always a pain. Will fix it later this week.

**Comment by ysmood** [comment]
Check my screen record, it's not leaking, can you share yours?


https://user-images.githubusercontent.com/1415488/102517051-e7ba7b00-40d2-11eb-8f2a-6404ce9d47ca.mp4

**Comment by BoladoDevelopment** [comment]
> Check my screen record, it's not leaking, can you share yours?
> 
> Kapture.2020-12-18.at.01.46.00.mp4

Code used: 
```
package main

import (
	"time"

	"github.com/go-rod/rod"
	"github.com/go-rod/rod/lib/launcher"
)

func main() {
	ch := make(chan int, 1)
for{
	ch <- 1
	go func() {
		
		launcher := launcher.New().
			Headless(false).
			Delete("use-mock-keychain").
			Set("start-in-incognito").
			Set("disable-gpu").
			Set("disable-audio-output").
			Set("disable-extensions").
			Set("disable-smooth-scrolling").
			Set("enable-low-res-tiling").
			Set("enable-low-end-device-mode").
			Set("window-size=400,500").
			Set("force-device-scale-factor=1").
			Set("no-sandbox").
			Set("disable-client-side-phishing-detection").
			Set("disable-default-apps").
			Set("disable-sync").
			Set("enable-ipv6").
			Set("disable-translate").
			Set("disable-prompt-on-repost").
			Set("safebrowsing-disable-auto-update").
			Set("disable-web-security").
			Set("disable-component-extensions-with-background-pages").
			Set("disable-background-networking").
			Set("no-default-browser-check").
			Set("test-type").
			Set("allow-outdated-plugins").
			Set("disable-renderer-backgrounding").
			Set("autoplay-policy=user-gesture-required").
			Set("disable-backgrounding-occluded-windows").
			Set("disable-threaded-scrolling").
			Set("disable-features=site-per-process, GlobalMediaControls, TranslateUI").
			Set("disable-client-side-phishing-detection").
			Set("disable-notifications").
			Set("disable-threaded-animation").
			Set("disable-hang-monitor").
			Set("metrics-recording-only").
			Set("ignore-urlfetcher-cert-requests").
			Set("winhttp-proxy-resolver").
			Set("disable-pnacl-crash-throttling").
			Set("disable-pepper-3d").
			Set("disable-dev-shm-usage").
			Set("check-for-update-interval=99999999").
			Leakless(true)

		url, _ := launcher.Launch()
		browser := rod.New().ControlURL(url).Trace(false).SlowMotion(500 * time.Millisecond).MustConnect()
		
		browser.MustPage("https://www.google.com")

		
	}()
}
}

```

rod: v0.85.6
leakless: v0.6.9

https://user-images.githubusercontent.com/74077743/102522100-9085bd80-4074-11eb-97e2-5527e29b306f.mp4

rod: v0.84.3
leakless: v0.6.8


https://user-images.githubusercontent.com/74077743/102523468-55848980-4076-11eb-86ee-96bcd62b222e.mp4

**Comment by ysmood** [comment]
@BoladoDevelopment Thanks for your report, should be fixed in https://github.com/go-rod/rod/releases/tag/v0.85.7

**Comment by BoladoDevelopment** [comment]
@ysmood No problem yad, always helping where I can.
I think the problem still persists, made the tests in a single video, but I think it was quite long, sorry.

https://user-images.githubusercontent.com/74077743/102653055-33116f80-414d-11eb-96d6-78d5d1827785.mp4

**Comment by ysmood** [comment]
If you use cmd to run the exe file and use ctrl-c to stop, it won't have any problem. Currently, the way you close it will cause the sub-process to exit, such as leakless will be killed before it has time to kill browsers.

**Comment by BoladoDevelopment** [comment]
> If you use cmd/powershell to run the exe file and use ctrl-c to stop, it won't have any problem. Currently, the way you close it will cause the sub-process to exit immediately, such as leakless will be killed before it has time to kill browsers.
> 
> I'm searching for a way to keep the guard sub-process running. On unix we can catch SIGTERM or SIGINT to do the cleanup, but no similar things for Windows.

The difference between 1.6.8 <> 1.6.9 doesn't tell anything? As on 1.6.8 still works beautifully.

Currently I'm being able to run the last version of rod placing a require for leakless 1.6.8 on my mod, its working quite good still.

**Comment by ysmood** [comment]
Yes, 1.6.8 will work because leakless is not killing the browser process, it uses special fork flags for the process, so the OS is actually the one that does the job.

**Comment by ysmood** [comment]
Confirmed a solution, use `cmd.exe /c start /b`. I will implement it when I have time, it requires to refactor the way we handle stdio, we have to use the TCP connection to pass the stdio.

**Comment by ysmood** [comment]
Should be fixed on the latest version, the code that solved it is here:

https://github.com/ysmood/leakless/blob/dd59b72d470952e3e7ac8ecceb7c94f2778de974/cmd/pack/main.go#L82-L83
